version: '3.8'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_DB=${SQL_DATABASE}
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        env_file:
          - .env.dev
    backend:
        build:
          context: .
        volumes:
          - type: bind
            source: .
            target: /code
        depends_on:
          - db
        ports:
          - 8000:8000
        env_file:
          - .env.dev
        command: python manage.py runserver 0.0.0.0:8000

volumes:
    postgres_data: