version: '2.4'

services:
    nginx: 
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - static_data:/static
        depends_on:
          - backend
        ports:
          - 80:80
          - 443:443
    db:
        image: postgres
        environment:
          - POSTGRES_DB=aasp
          - POSTGRES_USER=aasp
          - POSTGRES_PASSWORD=aasp
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    backend:
        build:
          context: .
        volumes:
          - type: bind
            source: .
            target: /code
          - static_data:/app/static
        depends_on:
          - db
        ports:
          - 8000:8000
        entrypoint: entrypoint.sh

volumes:
    postgres_data:
    static_data: