version: '3.8'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_DB=aasp
          - POSTGRES_USER=aasp
          - POSTGRES_PASSWORD=aasp
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    backend:
        build:
          context: .
        volumes:
          - type: bind
            source: .
            target: /code
        depends_on:
          - db
        ports:
          - 8000:8000

volumes:
    postgres_data: