# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-28 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AASPItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('wav_file', models.FileField(upload_to='')),
                ('text_grid_file', models.FileField(upload_to='')),
            ],
        ),
    ]
