# Generated by Django 3.0 on 2020-03-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AASPItem',
            fields=[
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('speaker', models.CharField(max_length=100)),
                ('wav_file', models.FileField(upload_to='input_files/')),
                ('text_grid_file', models.FileField(upload_to='input_files/')),
            ],
        ),
    ]
