# Generated by Django 3.0.7 on 2020-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AASPItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('speaker', models.CharField(max_length=100)),
                ('wav_file', models.FileField(upload_to='input_files/')),
                ('text_grid_file', models.FileField(upload_to='input_files/')),
                ('pitch_file', models.FileField(default=None, null=True, upload_to='input_files/')),
            ],
        ),
    ]
