# Generated by Django 3.0 on 2020-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaspitem',
            name='pitch_file',
            field=models.FileField(default=None, null=True, upload_to='input_files/'),
        ),
    ]
