# Generated by Django 3.0 on 2019-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaspitem',
            name='text_grid_file',
            field=models.FilePathField(match='*.TextGrid', path='/Users/janss089/DATA/Annotated_data_for_autoToDI/G4_V9_Esther'),
        ),
        migrations.AlterField(
            model_name='aaspitem',
            name='wav_file',
            field=models.FilePathField(match='*wav', path='/Users/janss089/DATA/Annotated_data_for_autoToDI/G4_V9_Esther'),
        ),
    ]
