# Generated by Django 3.0.7 on 2020-10-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_aaspitem_pitch_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaspitem',
            name='item_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='aaspitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
