# Generated by Django 3.0 on 2020-01-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20191209_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaspitem',
            name='text_grid_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='aaspitem',
            name='wav_file',
            field=models.FileField(upload_to=''),
        ),
    ]
